using Gulfy.Domain.Enums;

namespace Gulfy.Domain;

/// <summary>
/// A short link: maps a short code to a default destination URL, optionally
/// overridden per <see cref="Platform"/>, and tracks click/visit stats.
///
/// This is the aggregate root for the "link" concept — the only supported way
/// to mutate a ShortLink is through its methods, so invariants (e.g. a deleted
/// link can never be re-enabled) stay enforced in one place. See
/// ARCHITECTURE.md §5 for the ER diagram this maps onto.
///
/// Not thread-safe on its own: concurrent visits from multiple requests must be
/// serialized by the repository (task BE-03), e.g. via a per-key lock or an
/// atomic increment, before calling <see cref="RegisterVisit"/>.
/// </summary>
public sealed class ShortLink
{
    private readonly Dictionary<Platform, string> _platformDestinations;

    public Guid Id { get; }
    public string ShortCode { get; }
    public string OriginalUrl { get; }
    public string? CustomAlias { get; }
    public ShortCodeSource Source { get; }
    public DateTimeOffset CreatedAt { get; }

    public bool IsDisabled { get; private set; }
    public bool IsDeleted { get; private set; }
    public int ClickCount { get; private set; }
    public DateTimeOffset? LastAccessedAt { get; private set; }

    /// <summary>Per-platform destination overrides. Empty means "always use OriginalUrl".</summary>
    public IReadOnlyDictionary<Platform, string> PlatformDestinations => _platformDestinations;

    /// <summary>A link redirects only while it is neither disabled nor deleted.</summary>
    public bool IsActive => !IsDisabled && !IsDeleted;

    private ShortLink(
        Guid id,
        string shortCode,
        string originalUrl,
        string? customAlias,
        ShortCodeSource source,
        DateTimeOffset createdAt,
        Dictionary<Platform, string> platformDestinations)
    {
        Id = id;
        ShortCode = shortCode;
        OriginalUrl = originalUrl;
        CustomAlias = customAlias;
        Source = source;
        CreatedAt = createdAt;
        _platformDestinations = platformDestinations;
    }

    /// <summary>
    /// Creates a new active ShortLink with zero clicks. <paramref name="shortCode"/>
    /// and <paramref name="originalUrl"/> are assumed already validated/generated by
    /// the caller (Gulfy.Application) — this factory only guards the domain's own
    /// invariants, not URL-format or alias-charset rules.
    /// </summary>
    public static ShortLink Create(
        string shortCode,
        string originalUrl,
        ShortCodeSource source,
        DateTimeOffset createdAt,
        string? customAlias = null,
        IReadOnlyDictionary<Platform, string>? platformDestinations = null)
    {
        if (string.IsNullOrWhiteSpace(shortCode))
            throw new DomainException("ShortLink requires a non-empty short code.");
        if (string.IsNullOrWhiteSpace(originalUrl))
            throw new DomainException("ShortLink requires a non-empty original URL.");

        var destinations = platformDestinations is null
            ? new Dictionary<Platform, string>()
            : new Dictionary<Platform, string>(platformDestinations);
        destinations.Remove(Platform.Default); // Default always resolves to OriginalUrl below

        return new ShortLink(
            id: Guid.NewGuid(),
            shortCode: shortCode,
            originalUrl: originalUrl,
            customAlias: customAlias,
            source: source,
            createdAt: createdAt,
            platformDestinations: destinations);
    }

    /// <summary>
    /// Resolves the destination URL for a visitor on the given platform: the
    /// platform-specific override if one is set, otherwise <see cref="OriginalUrl"/>.
    /// Does not check <see cref="IsActive"/> — callers must check that first
    /// (see ARCHITECTURE.md §4, the redirect sequence).
    /// </summary>
    public string GetDestination(Platform platform) =>
        _platformDestinations.TryGetValue(platform, out var overrideUrl) ? overrideUrl : OriginalUrl;

    /// <summary>Records a visit: increments the click count and stamps LastAccessedAt.</summary>
    public void RegisterVisit(DateTimeOffset visitedAt)
    {
        ClickCount++;
        LastAccessedAt = visitedAt;
    }

    /// <summary>Stops the link from redirecting without discarding its history.</summary>
    public void Disable() => IsDisabled = true;

    /// <summary>Re-enables a previously disabled link. No-op on a deleted link.</summary>
    public void Enable()
    {
        if (IsDeleted) return;
        IsDisabled = false;
    }

    /// <summary>Soft-deletes the link. Deletion is permanent — there is no Undelete.</summary>
    public void MarkDeleted() => IsDeleted = true;
}
